'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OTG_Test_Harness.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v1.10.2 jquery.com | jquery.org/license */
        '''//load jQuery 1.10.2.min
        '''jQueryScript = window.document.getElementsByTagName(&quot;body&quot;)[0].appendChild(document.createElement(&quot;script&quot;));
        '''jQueryScript.setAttribute(&quot;language&quot;, &quot;javascript&quot;);
        '''jQueryScript.setAttribute(&quot;type&quot;, &quot;text/javascript&quot;);
        '''jQueryScript.setAttribute(&quot;src&quot;, &quot;http://code.jquery.com/jquery-1.10.2.min.js&quot;);
        '''
        '''/* 
        ''' * DOMParser HTML extension 
        ''' * 2012-02-02 
        ''' * 
        ''' * By Eli Grey, http://eligrey.com 
        ''' * Public domain. 
        ''' * NO WARRANTY [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HtmlToXml() As String
            Get
                Return ResourceManager.GetString("HtmlToXml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;root class=&quot;Fundraiser&quot; template=&quot;&quot;&gt;
        '''  &lt;givingLevels jQuery=&quot;$(&amp;quot;input[id$=&apos;1&apos;][type=&apos;radio&apos;]&amp;quot;)&quot; type=&quot;Click&quot; /&gt;
        '''  &lt;chkAnonymous jQuery=&quot;$(&amp;quot;input[id$=&apos;chkAnonymous&apos;][type=&apos;checkbox&apos;]&amp;quot;)&quot; type=&quot;Click&quot; /&gt;
        '''  &lt;chkMGCompany jQuery=&quot;$(&amp;quot;input[id$=&apos;chkMGCompany&apos;][type=&apos;checkbox&apos;]&amp;quot;)&quot; type=&quot;Click&quot; /&gt;
        '''  &lt;btnNext jQuery=&quot;$(&amp;quot;input[id$=&apos;btnNext&apos;][type=&apos;submit&apos;][class*=&apos;BBFormSubmitButton DonationSubmitButton&apos;]&amp;quot;)&quot; type=&quot;Click&quot; /&gt;
        '''  &lt;btnBack jQuery=&quot;$(&amp;quot;input[id$=&apos;btnBack&apos;][t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property mappingfile() As String
            Get
                Return ResourceManager.GetString("mappingfile", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
